### ISSUE TITLE
Add and Implement Calendar Export functionality within program GUI

### ISSUE THREAD

**Issue by AmilaDias** [rsanchez-wsu/RaiderPlanner#101]
As per issue #50 and pull request #71, the project can now export calendar events to ICS files. However, at the moment, this occurs upon launching of the Calendar utility, rather than upon user prompt.

An enhancement that could be made is to implement an "Export" button within the calendar view GUI. This button would be an action event that would trigger the export process implemented in PR #71.

**Comment by AmilaDias** [comment]
I am currently working on implementing this issue

**Comment by rsanchez-wsu** [comment]
@AmilaDias Was this issue considered closed when I merged your pull request (#125)?
