### ISSUE TITLE
Back button background

### ISSUE THREAD

**Issue by Aashishkebab** [rsanchez-wsu/RaiderPlanner#103]
The back button now has a background, but it doesn't seem to fit or make a lot of sense. It should be removed.

<img width="101" alt="screenshot_20171013-225240" src="https://user-images.githubusercontent.com/25588487/31571913-7160077e-b069-11e7-9f78-d7cd6342fa17.png">

**Comment by cameronroudebush** [comment]
I will work on this as part of my project 2.
