### ISSUE TITLE
Replace occurrences of "throws Exception"

### ISSUE THREAD

**Issue by rsanchez-wsu** [rsanchez-wsu/RaiderPlanner#108]
There are many occurrences of `throws Exception` throughout the code.  This is bad design.  Each one needs to be changed to `throws` followed by a list of one or more specific exception types which are thrown from that particular method.  This issue applies to occurrences under `src`.  Those under `Test` will need to be handled in conjunction with a more comprehensive rework of the test suite, which will be driven by a different issue.

**Comment by lakerimff** [comment]
I'll look into this!
