### ISSUE TITLE
UIManager class creates many instances for the same objects

### ISSUE THREAD

**Issue by rnunez95** [rsanchez-wsu/RaiderPlanner#111]
In the UIManager.java file there exists many instances in which the same objects gets called in different methods. Running a private static variable for all these once will improve performance and clean up code.

**Comment by rnunez95** [comment]
I will be working on this.

**Comment by Aashishkebab** [comment]
While you're at it, maybe you could refactor/rename the UIManager.java to something else (such as Interface.java), so as to fix a checkstyle issue?
