### ISSUE TITLE
Make window size based on screen resolution.

### ISSUE THREAD

**Issue by Aashishkebab** [rsanchez-wsu/RaiderPlanner#120]
Make the window startup size based on the resolution of the screen it is being viewed on. I claim this issue.

**Comment by cameronroudebush** [comment]
@Aashishkebab You are just talking about once it opens up the primary program to study dashboard and not the .dat file selector, correct?

**Comment by Aashishkebab** [comment]
@cameronroudebush Yes, but I have already fixed this issue and made a pull request. I forgot to self-claim this issue.
<img width="361" alt="screenshot_20171017-222116" src="https://user-images.githubusercontent.com/25588487/31698110-9c137e1a-b389-11e7-8a52-35e45bd4d99c.png">

**Comment by cameronroudebush** [comment]
@Aashishkebab Do you also have a mainStage.setMaximized(true)? If not you might also want to include that as the resizing you did just matches the stage to the screen size but it is technically not maximized like I think you are looking for.

**Comment by Aashishkebab** [comment]
@cameronroudebush I was trying to avoid maximizing the window. In fact, in this case, I was trying to make the window start at about 75% of the screen's width and 90% of the screen's height. Previously, it started out at an exact pixel count, which wasn't friendly to low-resolution screens. My screen is 1080p, but I have tested the program at 600p resolution and tried to optimize it. However, since you brought it up, I changed the semantics of the properties so that it is easier to understand what it is doing.
Here is it updated: 
<img width="430" alt="screenshot_20171017-224926" src="https://user-images.githubusercontent.com/25588487/31698945-173ea46c-b38e-11e7-8ebb-ef06ef078e77.png">

**Comment by eSweetTech** [comment]
I personally think that starting it in full screen or partial screen is argumentative and should be discussed with the entire class, or at-least people who are working on UI so that these changes won't end up getting truncated if people see them and dislike them. Their are advantages and disadvantages to a maximized screen, but I think these decisions need to be made by more than one person

**Comment by Aashishkebab** [comment]
@eSweetTech I am only changing the size it starts at, but I have actually improved ability to resize. 
Previously, the screen had a very restrictive minimum sizing, and I significantly reduced that.
Furthermore, previously the screen automatically started at an absolute 1,000 pixels in height. I reduced this and set this number to instead 75% of of whatever the current screen resolution is. 
This allows the application to respond differently based on different screens, so that low resolution screens don't suffer like they have been.

**Comment by eSweetTech** [comment]
That wasn't the point I was trying to make. I think that we need to have a more open dialog about what is happening for UI, whether that is starting a new channel on Slack or different means. Personally, I'm not working on UI, but I think it would be beneficial for everyone working on it and for anyone who wants to make their comments or concerns heard.

**Comment by Aashishkebab** [comment]
@eSweetTech Agreed, open dialog is good, I'm just afraid of how many people will actually participate in such dialog. My recent pull request made quite significant GUI changes. Take a look at #106. All of my pull requests have been GUI based, and I agree that more debate on this would help.

**Comment by rsanchez-wsu** [comment]
@eSweetTech @Aashishkebab I appreciate the points both of you made.  If there are specific concerns that we want to make sure do not slip through the cracks, then please create new issues that document specific items to discuss to changes to make.  However, as @Aashishkebab pointed out, we do need to be careful to avoid [bikeshedding](https://en.wiktionary.org/wiki/bikeshedding).
