### ISSUE TITLE
Add files to gitignore

### ISSUE THREAD

**Issue by Aashishkebab** [rsanchez-wsu/RaiderPlanner#127]
Add all ICS files, all .dat files, and the import_report.txt file to .gitignore.

**Comment by rkoeller** [comment]
I'll take care of this.

**Comment by Aashishkebab** [comment]
@rkoeller I technically did this already. It says I 'referenced this issue 6 hours ago', as I added these three lines to gitignore at that time in a commit. I'm sure there are many other items you can add to gitignore that I forgot to add in my pull request though (such as xml files for example).

You could probably add the above files as well, but it might cause merge conflicts.
