### ISSUE TITLE
Add a Help Button to the Menu

### ISSUE THREAD

**Issue by rkoeller** [rsanchez-wsu/RaiderPlanner#128]
This button should simply open the RaiderPlanner website in a web browser. This button could be updated at a later date to open the RaiderPlanner user manual if created or a FAQ page on the website.

**Comment by rkoeller** [comment]
I would like to do this.

**Comment by Aashishkebab** [comment]
Suggestion: Maybe you could add local help inside the application itself. Like a separate page or something.

Or maybe even load the website but inside the application (like a viewport for the website inside the application). This may be difficult as I have no idea how to do it.
Here is a GIMPed (PhotoShopped) general idea of what I mean.
<img width="1063" alt="viewport" src="https://user-images.githubusercontent.com/25588487/31750421-fa8791f6-b44d-11e7-9319-5c94d7f8cd0b.png">

**Comment by rkoeller** [comment]
I think that is a good idea and I've seen this implemented this way but I think the way I suggested is the far more common method. Is it really necessary to open the website inside RaiderPlanner? I will do it my suggested way if that's okay with you and then if its decided later on that it would be better for the website to open inside RaiderPlanner then we can submit an issue to update the button to do so.

**Comment by Aashishkebab** [comment]
Of course it's okay with me, plus it's only my opinion. Plus what I stated would be difficult to implement I imagine.

**Comment by rsanchez-wsu** [comment]
@rkoeller As I mentioned in class, if you are making GUI-related changes you need to post before/after screenshots of your change (or screencasts, if that makes more sense for your change).  Please upload them here so that I can finalize your pull request.

**Comment by rkoeller** [comment]
![before](https://user-images.githubusercontent.com/31522140/32702508-5faac5b4-c7b6-11e7-980b-f6eb728a7bf3.png)
![after](https://user-images.githubusercontent.com/31522140/32702507-5f9a94be-c7b6-11e7-8ec4-49449e46cae6.png)

**Comment by rkoeller** [comment]
![before](https://user-images.githubusercontent.com/31522140/32702557-ea8e43e0-c7b6-11e7-95c0-30e5da827b38.png)
![after](https://user-images.githubusercontent.com/31522140/32702556-ea83624a-c7b6-11e7-80e6-60998fe5c63d.png)
