### ISSUE TITLE
Change Header based off Tab

### ISSUE THREAD

**Issue by eSweetTech** [rsanchez-wsu/RaiderPlanner#132]
In the current implementation of the UI, the header is Study Dashboard, and in the different tabs such as Calendar, their is no header, but a sub-header inside of the grey area with that tabs name. This issue is for moving that sub-header into the green header portion of the UI similar to where Study Dashboard is seen when you first open the program.

**Comment by cameronroudebush** [comment]
I shall work on this!

**Comment by rsanchez-wsu** [comment]
@cameronroudebush Could you provide some before and after screen shots to show the change you made?

**Comment by rsanchez-wsu** [comment]
@cameronroudebush It is not immediately apparent to me what I am looking at in each screenshot.  Could you describe what has changed in each?

**Comment by cameronroudebush** [comment]
@rsanchez-wsu In the pictures above it moves the windows name (i.e. Calendar, Modules, Milestones, course names) into the top green header instead of having them below in a sub header wasting more space.
