### ISSUE TITLE
Open Ganttish Diagram inside of main project

### ISSUE THREAD

**Issue by eSweetTech** [rsanchez-wsu/RaiderPlanner#133]
In the current implementation of the UI, when a user clicks on "Generate a Ganttish Diagram" it opens it up full-screened in a new tab. This is poor design as we start looking at the mobile aspect of the project. The solve to this issue would be opening up the Ganttish diagram inside of the main program and including an option for the user to go back to the module where he chose to create it at (a simple back button).

**Comment by cameronroudebush** [comment]
I will look into this.

**Comment by cameronroudebush** [comment]
@rsanchez-wsu Not sure if you wanted a picture here as well but I'm going to add one anyways: 
![ganttish diagram](https://user-images.githubusercontent.com/25460877/31950979-d9af901c-b8aa-11e7-915a-3fa4442c138a.png)

**Comment by rsanchez-wsu** [comment]
@cameronroudebush Thanks.  The screenshot is helpful.

**Comment by rsanchez-wsu** [comment]
@cameronroudebush so, this looks strange on my machine:

![screenshot from 2017-11-12 15-56-24](https://user-images.githubusercontent.com/9941546/32703326-45f4c460-c7c2-11e7-87fb-bacbdf26a3f4.png)

I am going to accept your pull request, but I would like for you to write up a new issue for this strange appearance in the GUI.  You can look into it yourself or leave it for someone else.

**Comment by cameronroudebush** [comment]
@rsanchez-wsu I wasn't sure if this issue was another problem because #91 was supposed to fix this in other windows.
