### ISSUE TITLE
Remove secondary start-up Screen

### ISSUE THREAD

**Issue by eSweetTech** [rsanchez-wsu/RaiderPlanner#134]
Ref #129 
Currently when starting the project, the user is getting an option to create a new file, open a file or exit the program. If they choose to open or create a new file, after the prompts it loads them into the study dashboard. With this implementation, two windows are needed, which is causing issues in tablet mode on computers (Ref #129) and would cause issues during mobile implementation. The fix to this would be open up the creation/log-in prompt inside of the program. This will put the program into one window. After the user chooses their option, the program will go re-populate with the study dashboard information in the same window. This implementation may only be advantageous to the mobile platform, but could help solve the referenced issue, while also only needing one window to open. 

If this doesn't make sense, feel free to talk to me or Cameron.

**Comment by AlenaBrand** [comment]
I'm currently working on this.
