### ISSUE TITLE
Change notification Icon

### ISSUE THREAD

**Issue by eSweetTech** [rsanchez-wsu/RaiderPlanner#135]
The icon in the current state is a mail symbol with a white dot in the upper right hand corner, that turns red when their is a new notification. At first glance, the white dot can be noticed to be a notification since it is not a normal image people are seeing. The change for this would be to remove the current no notification icon with a similar icon with no white circle in the upper right hand corner. This implementation is very similar to pilot's notification system and other programs notification systems

Cameron will be working on this issue

**Comment by rsanchez-wsu** [comment]
@cameronroudebush This issue could use a set of before/after screenshots.
