### ISSUE TITLE
Access Restriction errors

### ISSUE THREAD

**Issue by DTCartier** [rsanchez-wsu/RaiderPlanner#138]
There are an abundant of errors that revolves around the jfxrt.jar. 
To resolve, javaFX needs to be accessible which is not configured or not configured correctly within the jar library. I shall look into this issue.

**Comment by rsanchez-wsu** [comment]
This is not really an issue with the project, since as long as Eclipse doesn't mess with the .classpath file, there is no problem.  I am closing this issue.
