### ISSUE TITLE
SimpleDateFormat in Event.setDate() needs to be thread-safe

### ISSUE THREAD

**Issue by rsanchez-wsu** [rsanchez-wsu/RaiderPlanner#152]
In #35, date validation in `Event.setDate()` was changed to use the `SimpleDateFormat` class.  However, that class is not thread-safe.  From the Javadoc:

```
Synchronization

Date formats are not synchronized. It is recommended to create
separate format instances for each thread. If multiple threads access
a format concurrently, it must be synchronized externally.
```

Access to the `SimpleDateFormat` object in the `Event` class needs to be done in such a way so as to allow for safe access by multiple threads.

If you decide to work on this task, please investigate the potential implementations and propose a solution here prior to beginning implementation work.

**Comment by sarasews** [comment]
I'm researching options for this.

**Comment by sarasews** [comment]
I propose using FastDateFormat in place of SimpleDateFormat. 

FastDateFormat was specifically made to replace SimpleDateFormat: to increase speed, be thread-safe, and it is immutable. There should be no need for additional synchronization. 
Some discussion I found online mentioned that it did not support parsing, but as of lang 3.2 parsing IS supported. 

[http://commons.apache.org/proper/commons-lang/javadocs/api-2.6/org/apache/commons/lang/time/FastDateFormat.html](url)

**Comment by rsanchez-wsu** [comment]
@sarasews I would be OK with that solution.
