### ISSUE TITLE
Optimize website for mobile

### ISSUE THREAD

**Issue by Aashishkebab** [rsanchez-wsu/RaiderPlanner#155]
While the website looks amazing, it needs work on mobile devices. Fluid design should be used. 
![screenshot_20171024-000712](https://user-images.githubusercontent.com/25588487/31924502-d5db6160-b84f-11e7-9a9a-b2c82e0c1537.png)
A media query can be used to aid in this. 

Also, the menu items should be aligned right here. 
![screenshot_20171024-001623](https://user-images.githubusercontent.com/25588487/31924589-a214f49e-b850-11e7-84c4-fb67af1dba6b.png)

**Comment by lakerimff** [comment]
If nobody has claimed this, i'll look into this

**Comment by lakerimff** [comment]
@Aashishkebab do you not think the menu on the mobile screen would look better centered rather than aligned right?

**Comment by Aashishkebab** [comment]
@lakerimff I think both could look good, you can experiment with them. It just can't be left aligned because the menu button is on the right.
Just make sure that if it's centered, then each item is a block item, so you can click anywhere horizontally on that item, and you should also separate them with horizontal lines I think.
