### ISSUE TITLE
Sizing bug

### ISSUE THREAD

**Issue by Aashishkebab** [rsanchez-wsu/RaiderPlanner#158]
The sizing bug found in #91 is still present, though to a lesser degree. Notice the title text going off center. In fact, anything you add to "this.maincontent" in the MainController class has this issue.
<img width="741" alt="screenshot_20171024-224701" src="https://user-images.githubusercontent.com/25588487/31978285-a6eb59a4-b90e-11e7-8d34-3f2d2c1f2c87.png">

@RachelHill8 Maybe you want to look into this some more? Your previous pull request definitely helped fix most of the problem.

**Comment by RachelHill8** [comment]
I can take a look at this again if you haven't already started. Sorry it took so long to reply.

**Comment by Aashishkebab** [comment]
That's totally cool, I haven't done anything with this. #165 is also related to this and more up to date.

**Comment by RachelHill8** [comment]
Since the titles have been moved to the navigation bar is this really an issue?

![image](https://user-images.githubusercontent.com/31511671/32909605-fb7df224-cad4-11e7-8ffa-bf45de191175.png)

**Comment by Aashishkebab** [comment]
@RachelHill8 Probably not, but whatever is causing the issue I'm guessing is related to #165 in some way. If you solve one, you'll probably end up solving the other, but I wouldn't know for sure.

**Comment by Aashishkebab** [comment]
This issue can be closed.
