### ISSUE TITLE
#91 still persists

### ISSUE THREAD

**Issue by Aashishkebab** [rsanchez-wsu/RaiderPlanner#165]
This issue #91 still persists in some areas, though it's definitely less noticeable. In fact, it seems to only occur on the Modules tab. The issue was mostly fixed by #117.
<img width="747" alt="screenshot_20171114-172400" src="https://user-images.githubusercontent.com/25588487/32808410-ef474c96-c960-11e7-8bec-54a6b883a9e7.png">

**Comment by RachelHill8** [comment]
That's really odd I swore I had tested it thoroughly. I will check this out as well.

**Comment by Aashishkebab** [comment]
@RachelHill8 it's more than likely not your fault, somebody else probably made a change that did this.

One of the changes I made was undone by someone else who didn't correctly sync their fork. Probably the same thing happened to you.

You can check your original file in the commit history and compare it with the current file to see what's been changed.
