### ISSUE TITLE
The import issue for View.UIManager in StudyPlanner

### ISSUE THREAD

**Issue by cljones** [rsanchez-wsu/RaiderPlanner#187]
ref #9  The import statement of View.UIManager is in the wrong order and it needs to be put in the Third Party Package group.
![newissue](https://user-images.githubusercontent.com/14806949/32986014-a7e28fc2-cc95-11e7-8147-ee9809bab2fd.JPG)

**Comment by nguyenvo8** [comment]
I will work on this one
