### ISSUE TITLE
Change the size of the chart on Module to have unity with the other charts

### ISSUE THREAD

**Issue by klemmert** [rsanchez-wsu/RaiderPlanner#202]
This is the chart on the module page:
![chart](https://user-images.githubusercontent.com/25559890/33236016-0dd71e36-d215-11e7-98c6-c42171da8336.PNG)

This is how we want it to look like:
![idealchart](https://user-images.githubusercontent.com/25559890/33236024-3d3ec5e8-d215-11e7-8f65-886385380250.PNG)

**Comment by klemmert** [comment]
I will be taking care of this issue

**Comment by Aashishkebab** [comment]
I believe this might be a duplicate to #165. I believe @RachelHill8 might be working on this.

**Comment by klemmert** [comment]
My bad, I didn't realize that.
