### ISSUE TITLE
Fix the 'ant test' target

### ISSUE THREAD

**Issue by rsanchez-wsu** [rsanchez-wsu/RaiderPlanner#21]
The build is currently broken because there is a problem with the `ant test` invocation.  The junit invocation needs to be fixed so that the unit tests will run and the build will succeed.

**Comment by Codeyjj** [comment]
I am interested in working on this issue. Is there anything specific I should keep in mind with the transition regarding Gradle. Since that is an issue as well.

**Comment by rsanchez-wsu** [comment]
@Codeyjj I don't think that there is anything specific.  I suspect that whatever the problem turns out to be with the 'test' target invocation that the solution will either carry over in the same form to the Gradle implementation or that it will be a very easy direct translation.  It is safe to proceed without too much though toward the Gradle end of things with regards to this task.

**Comment by Miller189** [comment]
I'm getting a failure at:

junit.framework.AssertionFailedError
    [junit]     at Model.PersonTest.validEmail(PersonTest.java:283)

 Is this a result of the Issue 24 fix?

**Comment by rsanchez-wsu** [comment]
@Miller189 It could be.  Can you post the complete error output?

**Comment by Miller189** [comment]
Soytenly!

 [junit] Testcase: validEmail(Model.PersonTest):     FAILED
    [junit] null
    [junit] junit.framework.AssertionFailedError
    [junit]     at Model.PersonTest.validEmail(PersonTest.java:283)
    [junit]
    [junit]

BUILD FAILED
C:\Users\DJ\Desktop\school\CEG3120 Sanchez\raiderplanner\build.xml:221: Test Model.PersonTest failed

Total time: 9 seconds

**Comment by rsanchez-wsu** [comment]
@Miller189 it looks like it could be related, but I cannot tell for sure since the test suite was not working previously.  I recommend you set `haltonerror="no"` temporarily in build.xml so that you can finish your work.  Once you everything working in terms of the 'test' target actually runs all of the unit tests, then switch it back before submitting your pull request.  We will need new issues to make sure the broken tests get investigated and fixed.

**Comment by rsanchez-wsu** [comment]
The merge of pull request #67 with commit 085f2ff (which moved the project from Ant to Gradle) and the subsequent removal of `build.xml` with commit be387b3 make this issue OBE.
