### ISSUE TITLE
Fix Input Validation on New User Screen

### ISSUE THREAD

**Issue by AlenaBrand** [rsanchez-wsu/RaiderPlanner#223]
In reference to issue #160 some validation mechanism should be inserted in the new user screen. As you can see from my screenshot, the user is allowed to make a file without a salutation, full name, email, and a random account number.
![screenshot 14](https://user-images.githubusercontent.com/29344475/34900540-eaff3580-f7ce-11e7-924b-104a8dbbafdc.png)
There should be some validation of the account number (using student UID or W number). In addition an alert dialog should be displayed in any of the following cases, instead of removing the ability to select OK:

- If the user doesn't enter a salutation
- If the user enters an incomplete or invalid email
- If the user enters an invalid account number

If the ability to select OK is removed from the user, they may not be able to determine what they entered incorrectly.

An alert dialog should also be displayed to make sure that the user doesn't want to enter their name, if they chose to leave the full name field empty. I think leaving the full name field empty is a viable option, for the time being, to allow users to protect their privacy.

**Comment by rsanchez-wsu** [comment]
In general I like the concept here and I definitely like the UI/UX improvement.  You are absolutely correct that simply disabling the OK button does not help the user determine what was done incorrectly.  That said, I recommend that you explore the necessity of each bit of information before making them required for entry to create a new account.

This is something that we will discuss in depth in a later lecture, but the general theme is that if you require users to enter information that they think should be optional, you run the risk of them entering garbage and reducing the value of the data.  Let me know if you have any questions or if you would like more specific guidance.

**Comment by AlenaBrand** [comment]
That's true. On a related note, Another thing that I noticed in working with the program is, the Salutation input is not listed as optional, but the user is allowed to create an account without it. That should probably be fixed for user clarification. The salutation should be labeled as optional because that may not be important to the user. In the project's current state, the ID number (w number), isn't entirely necessary. However, if we chose to add networking, and w number confirmation capabilities later, I think we should leave it on for ease of future editing. Also if we pursue networking, we should probably make the user's full name a requirement, but allowing for an empty name, or partial name now, may help us determine how much information users are willing to supply. Therefore later, when we implement networking, we can better determine which parts of a user's name should be required. I will defiantly start working on the alert dialog issue, as described in my initial post.

**Comment by rsanchez-wsu** [comment]
OK.  If you would like to start a wiki page on some of the larger features that this change may impact (e.g., chat and WINGS integration) and list the items there so that they don't get lost, that would be a good thing.  Something else that I would like to make sure is done as part of this issue is a review of the related unit tests.  The unit test suite is in rather poor shape at the moment and I would like for each feature-related change to improve or implement the corresponding unit tests.  For example, for this change we would want to make sure to exercise various valid and invalid inputs, checking to make sure that valid inputs are properly accepted and stored and that invalid inputs produce the expected exception or error.

**Comment by rsanchez-wsu** [comment]
@AlenaBrand As I have been reviewing some of the old issues in the project, I noticed that this is closely related to #30.  Please review that issue and ensure that both this issue and that issue are addressed as appropriate.  If your changes for this issue completely fix that issue, then the appropriate annotations should be made.  If not, make sure you document in that issue what things have been done and how it affects what is described in that issue.
