### ISSUE TITLE
Make ModelEntity and ModelEntity.open() abstract

### ISSUE THREAD

**Issue by rsanchez-wsu** [rsanchez-wsu/RaiderPlanner#224]
The class `ModelEntity` contains this method:

```
	/**
	 * Open the appropriate UI window for this class
	 * To be overridden by children.
	 */
	public void open(MenuController.Window current) {
	}
```

This is poor design as not all sub-classes of `ModelEntity` actually override that method.  Additionally, no direct instances of `ModelEntity` are created anywhere in `RaiderPlanner` (except for in a single unit test, which can be accomplished via different means).  The empty method body should be removed, the method declared `abstract` and the `ModelEntity` class itself should also be declared `abstract`.

Here is a proposed list of tasks for this:

- [ ] Make the `ModelEntity` class `abstract` and the `ModelEntity.open()` method `abstract`
- [ ] Confirm that all direct sub-classes of `ModelEntity` are instantiated somewhere in `RaiderPlanner` and for any that are not, likewise make them abstract
- [ ] Ensure all sub-classes of `ModelEntity` that do not currently override `ModelEntity.open()` override with an empty method
- [ ] Ensure all occurrences of the `open()` method in concrete sub-classes of `ModelEntity` have the `@Override` annotation
- [ ] Fix the instantiation of `ModelEntity` in the `ModelEntityTest` unit test so that a nested class is used in the unit test to sub-class `ModelEntity` and perform the necessary tests.

There may be other things that need to be done, but that is a good start.

**Comment by TheGeth** [comment]
Made the changes suggested to the best of my ability. Pull request pending.
