### ISSUE TITLE
Gradle Refresh Changes .classpath and .project

### ISSUE THREAD

**Issue by natcrossman** [rsanchez-wsu/RaiderPlanner#226]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;There are currently two distinct bugs inside our project which relate to the way the Gradle build file is set up. These bugs become apparent whenever a project is cloned from the GitHub repository or whenever, a developer refreshes the Gradle build. During either of these scenarios, the **.classpath** and **.project** file get modified in such a way that the project will no longer compile. See **Figure 1**

<div align="center"><img src ="https://user-images.githubusercontent.com/31453497/35166852-430642c6-fd21-11e7-88e2-5986b8ac7704.png" /></div>

**<div align="center">Figure 1: Modified files</div>**

- [x] **Bug 1: The ".classpath"**
<hr><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The contents inside of the <strong>.classpath</strong> that get modified are the internal settings for locating the JRE.  Currently, our project is designed to work with the default JRE, no matter what the current JRE is on that given system. We do this by the following line of code, demonstrated in <strong>Figure 2</strong>.

![second](https://user-images.githubusercontent.com/31453497/35167245-bcdb7d4a-fd22-11e7-822f-ccd9e0635432.png)
**<div align="center">Figure 2: Original code inside of the . classpath</div>**

Obviously, this allows our project to be tremendously versatile and flexible on many different systems, no matter which JRE is available. However, on refreshing the Gradle build, Eclipse spontaneously decides to re-specify the execution environment. Thereby, overwriting our settings and preventing our application from compiling. This is because our project can no longer find the required libraries. Therefore, one has to manually reset the project to the origin after the refresh. See **Figure 3** for the modified line of code in the **.classpath**.

![third](https://user-images.githubusercontent.com/31453497/35167355-2de491b6-fd23-11e7-806a-85df1817401d.png)
**<div align="center">Figure 3: Modified .classpath</div>**

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; I personally feel like, this problem likely arises somewhere inside of our Gradle build where we specify/allow eclipse to do this modification. This is because, the order and access rules get defined in our build and we can customize the access rules with the **eclipse.classpath.whenMerged {}** API. This would be the suggested area a developer would first look into when trying to fix this bug. 
<br>

- [x] **Bug 2: The ".project"**
<hr><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Meanwhile, a similar thing happens to the <strong>.project</strong> file.  Inside of the .project file there is an attribute called "name". Originally, this attribute holds the value of “RaiderPlanner.git”; however, when a Gradle refresh happens on the project the "name" attribute gets reassigned the value of “raiderplanner”. See <strong>Figure 4</strong> and <strong>Figure 5</strong> for a demonstration of this process. During my investigation of these bugs, I figured out that problem area lies inside of the <strong>settings.project</strong> file. See <strong>Firgure 6</strong>. This file contains only one line of code which sets the “rootProject.name” to “raiderplanner”. Then upon the refresh of the project this value is inserted into the <strong>.project</strong> "name" attribute. 

<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; One potential fix is to just change the hardcoded value for “rootProject.name” to “RaiderPlanner.git.”  This simple fix ensures whenever a Gradle refresh happens the value inside the .project does not get changed. However, doing this may cause other issues in our application and would need to be tested.<br>

![fourth](https://user-images.githubusercontent.com/31453497/35168050-98dcc630-fd25-11e7-873b-5e273abe27e3.png)
**<div align="center">Figure 4: Original .project file</div>**

![fith](https://user-images.githubusercontent.com/31453497/35168187-ffd9c630-fd25-11e7-8abe-e05e481a2489.png)
**<div align="center">Figure 5: Modified .project file</div>**

![six](https://user-images.githubusercontent.com/31453497/35170832-7faea08e-fd2f-11e7-8a64-106085a8baf2.png)
**<div align="center">Figure 6: Source of modification</div>**

**Comment by natcrossman** [comment]
I would prefer to work on fixing these bugs! I have already started on fixing them and I believe that I already have an idea of how to fix one of them. Could you assign me this! 
Regards
Nathaniel Crossman

**Comment by rsanchez-wsu** [comment]
@natcrossman Thank you for the exceptionally detailed write up.  This bug has been annoying me since we switched to Gradle a few months ago and I would be thrilled if we could find a way to fix it.

**Comment by natcrossman** [comment]
This issue has been successfully migrated into our application.
