### ISSUE TITLE
Fix website - Several issues

### ISSUE THREAD

**Issue by Aashishkebab** [rsanchez-wsu/RaiderPlanner#227]
This is extremely generic, but the website has many issues that need to be fixed.

1. Font size is a percent, which it shouldn't be, as it causes the font to be egregiously large on larger screens. It should be fixed in units of "em". There is almost no situation where font size should be dynamic in this way.
![screenshot_20180119-160534](https://user-images.githubusercontent.com/25588487/35171671-9c8e9d1e-fd32-11e7-954f-d71b379174c6.png)

2.  Image widths are percentages, and this should be avoided, and rather image size should be dictated by the actual size of the image. Sizing the image via CSS should be avoided.
3. Certain images (such as the logo) scale width but not height, causing stretching/compression. 
![screenshot_20180119-160439](https://user-images.githubusercontent.com/25588487/35171639-7fbed140-fd32-11e7-9d64-6db8f859d0ee.png)

4. Download button on the Download page needs to not look spammy.
5. Download button needs to actually link to a downloadable (such as a jar) file.
6. Please no green text on gold background. Just no.
7. Video on Downloads page needs to be moved to the Home page.
8. Remove the copyright footer, unless the website actually has legal copyright protection.
9. The "Legal Terms" on the "Contribute" page are almost all invalid, and should be removed. All public GitHub repositories are allowed to use, display, and perform the Content through the GitHub Service and to reproduce the Content solely on GitHub as permitted through GitHub's functionality (for example, through forking). Furthermore, PearPlanner has adopted a GNU General Public License, which grants others even more right in what they can do. https://github.com/rsanchez-wsu/RaiderPlanner/blob/master/LICENSE.md
10. Random green underline appears under the navigation menu at certain screen widths. Remove. 
![screenshot_20180119-162147](https://user-images.githubusercontent.com/25588487/35172250-de4982da-fd34-11e7-9ee8-ab42a95375a3.png)
11. The footer actually needs to be at the bottom of the page. 
![screenshot_20180119-162319](https://user-images.githubusercontent.com/25588487/35172311-1c023cc0-fd35-11e7-9525-3bb1cdb384fd.png)

**Comment by NeiSabrina** [comment]
I can work on this issue.

**Comment by Andarific** [comment]
Hi @NeiSabrina, are you still working on this issue? If not, I can work on it.

**Comment by rsanchez-wsu** [comment]
@Andarific It has been 2.5 months, so it seems a safe bet that you can go ahead and work on it. @NeiSabrina Please speak up very soon if you are in fact still working on this or you will end up with conflicting changes.
