### ISSUE TITLE
Chat: Allow Message to Send with Enter Key

### ISSUE THREAD

**Issue by MichaelPantoja** [rsanchez-wsu/RaiderPlanner#229]
The goal of this issue is to add a minor enhancement to the chat feature. 

Currently, on the chat screen, when typing a message, you must click the send button to send the message. It would be an enhancement of convenience to be able to send the message by hitting the enter key.

**Comment by rsanchez-wsu** [comment]
@MichaelPantoja This issue does not really meet all of the guidelines for a good issue.  Please split this into two distinct issues.  I recommend that you improve #243 for the inability to return to the dashboard and that you write a new separate issue for the chat feature enhancement.

**Comment by CMorgan272** [comment]
I would like to take a look at this.

**Comment by rsanchez-wsu** [comment]
@CMorgan272 Note that the description of this issue needs to be improved (along with that of #243) to be sufficiently detailed and to meet the criteria of a good issue write up before making the change.

**Comment by rsanchez-wsu** [comment]
@CMorgan272 That sounds good.
