### ISSUE TITLE
Add 'run' target to build.xml

### ISSUE THREAD

**Issue by rsanchez-wsu** [rsanchez-wsu/RaiderPlanner#23]
Currently, in order to execute the _RadierPlanner_ application it is necessary to build the application by first invoking `ant all` and then by invoking Java directly from the command-line, including manually setting the classpath.  To make invoking the application easier for the development team, `build.xml` needs a new `run` target which will handle properly setting the classpath and then launch the application through the proper entry point.

**Comment by aar118** [comment]
I'm currently working on this.
