### ISSUE TITLE
Implement a Settings Menu

### ISSUE THREAD

**Issue by Collin-Thomas-WSU** [rsanchez-wsu/RaiderPlanner#238]
It would be Inspiring to put a Settings Menu within the RaiderPlanner. Here the user could edit their account in the case of misspellings or adding more information (i.e. their email, a salutation, account number, even the user's name).

The Default file could also be adjusted here, as discussed in issue #234.
Make issue #225 a toggle disable switch (is ON/Checked by default).

**Comment by rsanchez-wsu** [comment]
@Collin-Thomas-WSU This seems like a fairly large issue.  I imagine that as the design discussion proceeds and implementation decisions are made this issue will need to be split into smaller issues that can be reasonably implemented.  Also, please make sure you are familiar with issue #14 , which is for implementation of an application preferences system.  Your idea sounds closely related to that as well.

**Comment by Terrillc13** [comment]
I am currently working on this. 
Attached is how it looks like thus far:

![settingspreview](https://user-images.githubusercontent.com/35238135/35758137-5bdab140-0840-11e8-9beb-27504818891f.PNG)

I have decided to create it as its own FXML to provide an ordered appearance. The sidebar may be used to select different sections of the settings menu. The settings menu may be reached by the main menu by clicking a 'Settings' button on the sidebar. Attached is how the main menu has changed:

![mainmenupreview](https://user-images.githubusercontent.com/35238135/35758916-5dfc4732-0844-11e8-8bdb-0850a7cab87c.PNG)

If anything else should be added or anyone else has any other ideas, please let me know.
