### ISSUE TITLE
Fix email address validation (the current implementation makes my eyes bleed!)

### ISSUE THREAD

**Issue by rsanchez-wsu** [rsanchez-wsu/RaiderPlanner#24]
The current approach to email address validation makes my eyes bleed, and I say this as a self-proclaimed regular expression aficionado.

Completion of this issue requires the following:

- [ ] Read this article: https://www.linkedin.com/pulse/name-email-validation-you-doing-wrong-roberto-c-sánchez (yes, I am the author of that article, and you also need to read the articles linked directly from that article)
- [ ] Have a look at the current email validation logic (in Person.java:186-202)
- [ ] Bandage your eyes until the bleeding stops
- [ ] Update the email validation to use the Apache commons-validator (latest version) `EmailValidator` class

**Comment by eSweetTech** [comment]
I'll read up on and work on this issue
