### ISSUE TITLE
Implement Help Page/FAQ

### ISSUE THREAD

**Issue by RichardSimmons** [rsanchez-wsu/RaiderPlanner#240]
Currently clicking on the Help function within Raider Planner redirects the user to the the home page of the Raider Planner website which does not provide immediate help or information about an issue. 

![raider help](https://user-images.githubusercontent.com/9275322/35202396-80c0734a-fef0-11e7-8c78-e1fb1b9734c2.png)

In order to improve user experience the help button should:

1. Direct the user to  a page with frequently asked questions
2. Direct the user to common troubleshooting imformation
3. Direct the user to a  page with important information about the product.

**Comment by rsanchez-wsu** [comment]
@RichardSimmons @AndrewVaughn reported in #228 that this just doesn't work.  Could the two of you get together and figure out what is really happening?  Once that is done, I would be open to suggestions for improving the help feature.

**Comment by Collin-Thomas-WSU** [comment]
Have the help button link to the wiki page.

**Comment by AndrewVaughn** [comment]
If no one is working on this, I will get started on the enhancements.

**Comment by j-m-shaw** [comment]
Alex, Dan, and I would like to take a swing at this.

**Comment by rsanchez-wsu** [comment]
@j-m-shaw What is the proposed solution?

**Comment by j-m-shaw** [comment]
Clicking the help button would pop open a dedicated help gui, similar to ones that are present in windows applications. This gui would have a simple set of instructions available for the user to help them get started, along with a brief explanation of what RaiderPlanner is, and additional resources for the user in the event that the information in the gui is not sufficient. These additional resources would include the user-manual pdf in the RaiderPlanner directory, and a link to the website.

**Comment by rsanchez-wsu** [comment]
This issue was actually closed by 5b9f3c28d7805110f9b120dec1951beb7f8d3e78.
