### ISSUE TITLE
HTML Files Don't Pass Validation Check

### ISSUE THREAD

**Issue by NeiSabrina** [rsanchez-wsu/RaiderPlanner#241]
Right now, none of the html files are valid. Valid html files are less likely to cause problems in different browsers and create a smooth functioning website.

Some of the problems include:
1) Inconsistent doctype tags.
2) Images don't include alt tags.
3) Duplicate tags.
4) Beginning tags without a matching ending tag.

You can see all problems by uploading the html files and checking them here: 
https://validator.w3.org/

Also index.html and download.html are currently using HTML 4 while contribute.html and about.html use HTML 5. This can be fixed by changing the doctype tag from <DOCTYPE HTML!> to !DOCTYPE HTML. 
I think it would be good for all the html files to use HTML 5.

**Comment by rsanchez-wsu** [comment]
Amazing.  I completely forgot to check the validity of the website content when I merged it in.  Good catch.

**Comment by Andarific** [comment]
I can work on this issue.
