### ISSUE TITLE
Simplify Methods 'newFileB' and 'openFileB' in StartupController.java

### ISSUE THREAD

**Issue by Watson1995** [rsanchez-wsu/RaiderPlanner#242]
In the class StartupController.java, 'newFileB' method from lines 86-104 is four 'if' statements. 
This same thing applies to the method 'openFileB' from lines 116-135. I feel this could be 
greatly simplified by using '&&'. For example, in the 'newFileB' method, on line 86 it says 
if (plannerFile != null){ then the next line (87) is another if statement that says 
if(plannerFile.getParentFile().exists(). I feel these two lines can be simplified to one 
line, being; if((plannerFile != null) && (plannerFile.getParentFile().exists())). I feel this problem 
may exist in many classes. Obviously it is not a major issue as the code will work either way 
but I feel it may be a good idea for us to simplify methods if possible as it will make it easier 
to understand how the code is working. It will also provide a better understanding for the 
many students who may being doing this class and project in the future.

**Comment by rsanchez-wsu** [comment]
@Watson1995 I definitely agree with simplifying the code.  However, your issue write up is all one line.  Please edit it so that the formatting is correct.
