### ISSUE TITLE
Fix "welcome back" text on dashboard

### ISSUE THREAD

**Issue by rsanchez-wsu** [rsanchez-wsu/RaiderPlanner#264]
The below screenshot exhibits two bugs with the initial dashboard display:

1. The text always says "welcome back" even the very first time a user sees it, e.g., just after initial profile creation.
1. If the user declines to provide a name, then the message looks awkward: `Welcome back, !`

![screenshot from 2018-03-04 09-26-52](https://user-images.githubusercontent.com/9941546/36946678-5568d318-1f8e-11e8-88cb-3c30c373f56a.png)

The text should say "welcome" the very first time and "welcome back" on subsequent occurrences. This will require a bit of persistent state in the application.

As for dealing with a null or non-existent user name, if the user's name is not given (i.e., null) or empty (i.e., consists only of whitespace), then the text should say only `Welcome!` or `Welcome back!` as appropriate.

**Comment by Andarific** [comment]
I can work on this.
