### ISSUE TITLE
Calender Uninitialized at start-up

### ISSUE THREAD

**Issue by redfox2045** [rsanchez-wsu/RaiderPlanner#265]
As of currently when the calendar button is enabled at the start of a fresh save file attempted use of the Calendar results in a slew of errors caused by the Calendar not being initialized or substantiated when the program initially starts resulting in a Null Pointer Exception. The calendar variable appears to be first initialized on line 40 of the StudyProfile.java file in the Model, however there doesn't seem to be anything else done with it unless a profile is imported, which restores full functionality to the calendar. As of currently the only code handling the calendar is to import it, there is no way currently to handle a new one. Though part of that may be the screen sizing issue preventing the creation of a new study profile, but I was unable to find anywhere that code exists to actually create a new Calendar. 

**Note that this feature can only be accessed after turning the button disable off in the updateMenu() method of the MenuController.java file. 

![bug2a](https://user-images.githubusercontent.com/22842195/37182591-06889100-2300-11e8-9c3f-a044c3242dfe.PNG)
![bug2b](https://user-images.githubusercontent.com/22842195/37182592-0697e5f6-2300-11e8-88e4-4538ec78b4ab.PNG)
![bug2c](https://user-images.githubusercontent.com/22842195/37182593-06a4663c-2300-11e8-927f-4f91010f43b6.PNG)
![bug2d](https://user-images.githubusercontent.com/22842195/37182594-06b096e6-2300-11e8-8a44-6ee531384508.PNG)

**Comment by jordanjclay123** [comment]
I'll work on this issue.
