### ISSUE TITLE
The chat feature has no input checks, and doesn't resize

### ISSUE THREAD

**Issue by redfox2045** [rsanchez-wsu/RaiderPlanner#268]
As of currently there are no checks to ensure any info was inputted into the chat so as of currently you can enter the chat without actually inputting any data at all. If this is done the user is still able to post to the existing chat feature under the username null. I'd be interested in seeing what happens if you have more than one null in the same chat at the same time, but because almost all of the chat is currently placeholder there is obviously no way to really find that out. Additionally when resizing the window horizontally the Send button compresses down to become unreadable, this should stay at least large enough to be read no matter how small the window gets. 
![bug6a](https://user-images.githubusercontent.com/22842195/37183989-e1369bb6-2306-11e8-912d-233d400ac308.PNG)
![bug6b](https://user-images.githubusercontent.com/22842195/37183991-e142c274-2306-11e8-9538-4986c1c6b6d7.PNG)

**Comment by Andarific** [comment]
I'll work on this.
