### ISSUE TITLE
Change Icon to Raiders Logo

### ISSUE THREAD

**Issue by Miller189** [rsanchez-wsu/RaiderPlanner#28]
The pear icon looks great, but is not really appropriate for our branch of this project.  We should replace the icon with something a little more "Raider-y".

**Comment by eSweetTech** [comment]
Isn't this already part of #5?

**Comment by rsanchez-wsu** [comment]
As @eSweetTech pointed out, this is already covered in #5.  I am going to close this is a duplicate, since the icon itself probably doesn't need to be handled in its own issue.

**Comment by Miller189** [comment]
Whoops

**Comment by rsanchez-wsu** [comment]
@Miller189 No worries.  It happens.  Better to close a dupe than to miss something entirely because the issue never got written.
