### ISSUE TITLE
Study Profiles: Implement ability to remove an entire Study Profile

### ISSUE THREAD

**Issue by Watson1995** [rsanchez-wsu/RaiderPlanner#290]
When viewing the Study Profiles imported. You have the capability to select a profile as shown below.

![thumbnail](https://user-images.githubusercontent.com/25064903/38471514-2bb90254-3b40-11e8-8dc9-e75d21c46696.png)

Once you select a profile you can either set the profile as current, or just an 'ok' button to close the window

![thumbnail 1](https://user-images.githubusercontent.com/25064903/38471526-77ea8936-3b40-11e8-9619-89cc65de5cea.png)

I feel it is needed to implement a method that allows the user to delete the entirety of a study profile. The end state would have an additional button above the 'Set as Current' button that reads 'Remove Profile'. When this button is clicked, the entirety of the study profile selected will be removed. For example, the image above has two study profile, 2018 Spring Semester and First Year Gryffindor. Lets say we wanted to remove the entire 2018 Spring Semester study profile, once we click the 'Remove Profile', the profile should no longer be displayed in the table.

**Comment by Watson1995** [comment]
I will be working on this

**Comment by tbugaj444** [comment]
team patriot on it(Westfall and Bugaj). i assume @Watson1995 is no longer working here

**Comment by rsanchez-wsu** [comment]
That is a safe assumption.
