### ISSUE TITLE
Project/fork rename: PearPlanner -> RaiderPlanner

### ISSUE THREAD

**Issue by rsanchez-wsu** [rsanchez-wsu/RaiderPlanner#3]
The upstream project from which this project was forked is called _PearPlanner_.  For the purposes of the project as developed under this fork, the name will be _RaiderPlanner_.  There are numerous occurrences of the string "PearPlanner" in the code base which need to be replaced with "RaiderPlanner".

It is necessary take care when changing the references to account for variable names, paths, or other references within the code which may not work with a simple search and replace.  Additionally, the README.md in the project root should not be subjected to a blind search and replace.  Rather, it should be updated to explain the origin of the project and its current state.

**Comment by rnunez95** [comment]
Looks like one I can tackle.
