### ISSUE TITLE
JavaFX Error Message after quitting program with nothing entered at first use

### ISSUE THREAD

**Issue by wkiger** [rsanchez-wsu/RaiderPlanner#303]
Upon first launch of the program, the user should be able to immediately quit the program without receiving a JavaFX error message allerting them: 

<img width="357" alt="screen shot 2018-09-07 at 9 51 40 am" src="https://user-images.githubusercontent.com/23282379/45222913-c62b8180-b283-11e8-8b2e-c644b88ec15a.png">

This error message is triggered the exception handling at line 124 in the UiManager.java file.  The MainController.java file chatches the error at line 257 I believe.  This logic needs to be addressed for a cleaner user-interface and exit at first use of the program.

**Comment by rsanchez-wsu** [comment]
@wkiger How did you launch the application that you encountered this error dialog?

**Comment by wkiger** [comment]
@rsanchez-wsu I launched the program from main and immediately exited the program with the exit button in the pane.  That was what triggered the error pane.  At that point, I had entered no information into the program.

**Comment by rsanchez-wsu** [comment]
Did you launch through Eclipse or via `gradle run`?

**Comment by wkiger** [comment]
I launched the program through Eclipse.

**Comment by gagegage926** [comment]
Picture of the stack trace for reference

![45269567-50c7d880-b45e-11e8-8972-ad2d3fd44199](https://user-images.githubusercontent.com/5930101/45363268-1452c480-b5a5-11e8-88f7-3de0b2461255.PNG)

**Comment by rsanchez-wsu** [comment]
@gagegage926 that is helpful.  However, in the future, it is better to paste the text instead of an image.

**Comment by GGanris** [comment]
I'll work on this.
