### ISSUE TITLE
MainController.java missing documentation

### ISSUE THREAD

**Issue by Neon-Skyfire** [rsanchez-wsu/RaiderPlanner#307]
I was getting some errors when I tried to make a save file and I tracked the error to the loadfile method in the MainController.java file in the controller package.  This method has a bunch of different catch statements with only a short and in some cases vague error message for each.  I think these should have at least a little documentation explaining the purpose of each catch statement so it is easier to understand the source of the error.  Also a few of the error messages have spacing issues.

**Comment by hippytech127** [comment]
I'll tackle this issue
