### ISSUE TITLE
Sign in: Failed to load file - Bug

### ISSUE THREAD

**Issue by Spunspin** [rsanchez-wsu/RaiderPlanner#311]
Issue #263 removed the startup screen that asked users to create a new profile or open an existing one. In doing so it has introduced a bug that prevents new users from creating save data and thus they are unable to use the application. Some of the knock-on effects of this have been referenced in issues #303 and #306. Fixing this problem is crucial so that new users may interact with the application. 

After the merge of issue #263 user data would not be saved in the "saves" folder 
![ex1](https://user-images.githubusercontent.com/25639842/45261453-ca18ea00-b3d0-11e8-8a2e-7e0a2dc55c8d.png)

![ex2](https://user-images.githubusercontent.com/25639842/45261455-d3a25200-b3d0-11e8-8f24-140ddd13f6df.png)

Before the merge data is saved successfully 
![ex3](https://user-images.githubusercontent.com/25639842/45261456-d735d900-b3d0-11e8-9fde-11019bf21825.png)

![ex4](https://user-images.githubusercontent.com/25639842/45261458-da30c980-b3d0-11e8-8767-f80f92463559.png)

**Comment by rsanchez-wsu** [comment]
@Spunspin Fantastic issue write up.  Thanks for capturing this.

**Comment by mikeknows** [comment]
Group1 is working on this.
