### ISSUE TITLE
New Requirement's "Ok" button unlocks, even with errors in fields.

### ISSUE THREAD

**Issue by D-B-Cooper** [rsanchez-wsu/RaiderPlanner#313]
When Creating a new requirement, if the fields are filled out wrong, the ok button will still unlock. It will not allow users to save the information, however it also does not provide an explanation as to why the fields are wrong.
In order for this issue to be resolved, the "OK" button should not be unlocked until all information entered has been verified. Also, when an incorrect entry has been made, there should be some explanation as to why it is wrong.

EDIT: Also throws exceptions due to trying to process incorrect input.

![new req bug](https://user-images.githubusercontent.com/42809717/45266263-5bff1200-b426-11e8-9f3b-81229206b52e.PNG)

**Comment by rsanchez-wsu** [comment]
@D-B-Cooper I agree that if the OK button is going to be enabled/disabled depending on the validity of the input that it should only enable when the input is actually valid. Do you have an idea/suggestion for how to give the user feedback on the bad input?

**Comment by D-B-Cooper** [comment]
@rsanchez-wsu There seems to be enough space underneath the two boxes to have a small, meaningful error message if the user leaves an incorrect response/format in a box. This would be a discussion for the team, as (for the sake of consistency) the same format should be applied to any similar user input.

**Comment by rsanchez-wsu** [comment]
That would work.  However, since we already have the red highlight, another possibility would be to add a tool tip indicating the problem with the input.
