### ISSUE TITLE
Initial Startup Issues

### ISSUE THREAD

**Issue by iWinfrey** [rsanchez-wsu/RaiderPlanner#317]
Upon running the program, there were some issues with the UI. For the text fields, even though each one tells what information needs to be filled in, it doesn't entirely help that it goes away as you're typing. It would help if users would be able to see what field needs to be filled in outside of each of the text fields. Sometimes people could forget what information needs to be filled in as they're typing. Not to mention displaying the word limit for the number of characters that need to be typed in would help the user understand the requirement. There is also a checkbox field that says "Family name last?". That could be interpreted as more than one meaning than what it was originally intended to be. Either the text needs to be worded better or just remove it all together. The field for the salutation is also pretty vague. I don't understand the need for it or what it will be used for in making the account. I believe that could also be more clear.

**Comment by rsanchez-wsu** [comment]
These are some interesting suggestions.  I see some overlap with other issues, so make sure that we are not duplicating effort as we work on this.

**Comment by rsanchez-wsu** [comment]
Closed by #360
