### ISSUE TITLE
Resolve Typecast Safety Warnings

### ISSUE THREAD

**Issue by barrett-matthew** [rsanchez-wsu/RaiderPlanner#32]
Related to issue #20 

In the current project, there are several problems involving typecasting. For example, in HubFile.java, there is a cast on line 156 which is not validated. While it is probably unlikely that this cast will fail, the large number of these checks that are absent in the project warrants a resolution. The issue can be further broken down as follows.

- [ ] Resolve all cast issues created from casting Node to T.

- [ ] Resolve all cast issues created from casting Object to ArrayList<>.

- [ ] Ensure that the affected files continue to perform their functions properly.

**Comment by DTCartier** [comment]
Looking into this.

**Comment by barrett-matthew** [comment]
@DTCartier are you still working on this assignment? If not, I think I'd like to take a stab at it.

**Comment by DTCartier** [comment]
Hey @barret-matthew,  I've put in a PR regarding this issue but I'm still trying to figure out issue #20.

**Comment by rsanchez-wsu** [comment]
@DTCartier Can you tell me which pull request it was?

**Comment by DTCartier** [comment]
@rsanchez-wsu The PR was #77. You closed the issue but did not merge.
