### ISSUE TITLE
Unable to Add Task to Planner

### ISSUE THREAD

**Issue by jwilliamsrapper** [rsanchez-wsu/RaiderPlanner#322]
I ran the planner application and the tried to test adding a task but it did not work. Even after I created an account the add task or to better put it the "+" button still did not work/unlock.

Steps that lead to bug
 - Run program from Main.java file
 - Create new account 
 - Click The "+" to attempt to add new task
![image](https://user-images.githubusercontent.com/32585789/45314317-65a87880-b4ff-11e8-8c17-9c12c1083344.png)

As you can see the plus "+" button in the top right corner does not unlock or become clickable. Either functionality needs to be added to that button or functionality needs to be fixed for that button.

**Comment by rsanchez-wsu** [comment]
This issue lacks sufficient detail to be useful.  It sounds like you are describing buggy behavior, in which case a list of clear and unambiguous steps to reproduce would be necessary.  Annotated screen shots would also help.

**Comment by rsanchez-wsu** [comment]
Thanks for editing the writeup and adding some more detail.  That is very helpful.

**Comment by GGanris** [comment]
I will work on this.
