### ISSUE TITLE
Add a Dedicated Help Page

### ISSUE THREAD

**Issue by RichardSimmons** [rsanchez-wsu/RaiderPlanner#327]
Currently the help button redirects the user to the home page of the Raider Planner website. I propose creating  a help tab on the Raider Planner website to better help the user understand the program.
![raiderplannerhelp](https://user-images.githubusercontent.com/9275322/45271071-ecaf0f80-b471-11e8-9233-b62feaeb638a.png)

**Comment by rsanchez-wsu** [comment]
Good idea.  However, this needs quite a bit more detail to make it something that can be implemented.  Could you suggest some topics that should be included in the new help section?

**Comment by CMorgan272** [comment]
I would like to take on this issue. Currently in the Final Documents folder of RaiderPlanner there is a User Manual pdf
[User Manual.pdf](https://github.com/rsanchez-wsu/RaiderPlanner/files/2394491/User.Manual.pdf)
 that is out of date and still has the PearPlanner information I would like to update this to RaiderPlanner and add it to the https://rsanchez-wsu.github.io/RaiderPlanner/index.html as a user guide.

**Comment by RichardSimmons** [comment]
If you provide a more detailed "How-to" guide with the program. I can provide a more general overview of the features and some frequently asked questions about the program that can be added as a separate page on the website or combined with the User Manual pdf.

**Comment by rsanchez-wsu** [comment]
@RichardSimmons That sounds good.

**Comment by rsanchez-wsu** [comment]
The pull request I just merged closes this issue.
