### ISSUE TITLE
Fix notifications mark-as-read button

### ISSUE THREAD

**Issue by Bhulbert2096** [rsanchez-wsu/RaiderPlanner#33]
When you run the program and click in the top right hand corner on the notifications button it drops down notifications. When the mark all as read button is clicked nothing happens. We should solve this problem and then look into updating the notification button similar to pilots.  Such as red when you have new notifications and nothing when there is nothing new. 

1)Fix the mark all as read button
2)update the notification button logo on the UI

**Comment by RandyForte** [comment]
I tested and this works fine for me. The logo is also red when there are new notifications.

**Comment by rsanchez-wsu** [comment]
@Bhulbert2096 @RandyForte You two should try to reach a consensus on what is happening and then what the correct behavior should be and whether it needs to be fixed or changed.

**Comment by RandyForte** [comment]
Okay when I have new notifications and click the mark as read they are marked as read. Also when I have unread notifactions I am displayed notifaction1.png, when there are no unread notifications I am displayed notifaction0.png. @Bhulbert2096 When are you these features not working for you? Sounds like there might be a bug fix here. If you can help me recreate the bug ill try and help you find it.

**Comment by Bhulbert2096** [comment]
@RandyForte I see my mistake. I had assumed that at first running the program I looked and there was 2 things already in the notifications pulldown.  It turns out that those were not actual notifications they dont actually disappear.  I ran what you did randy and I got it to work. It was an oversight on my part and thank you for catching that.
