### ISSUE TITLE
Rework Date Validation

### ISSUE THREAD

**Issue by aar118** [rsanchez-wsu/RaiderPlanner#35]
### The Problem:
The code in Event.java in the directory of src/Model really needs to be fixed up. The regex isn't too bad, but all of the isNumeric(); function calling, true checking, and substringing is completely unnecessary.

### Possible solution:
In Java 2 we learn how to use the SimpleDateFormat class. I think we can use that to get exactly the date format we want, and then use a try-catch block to try to parse the date string into a date object.

There are, of course, other possible solutions than using SimpleDateFormat. It's exactly how it's called though: simple. I just don't want to see a bunch of function calling and if statements to achieve something that Java already has built-in to do.

**Comment by rsanchez-wsu** [comment]
@aar118 This is good.  For the sake of completeness and thoroughness of design, please consider and then document here how the exceptional case should be handled.  That is, if the exception is thrown, what should the application do?

**Comment by sarasews** [comment]
I'm going to look into this.

**Comment by eSweetTech** [comment]
With implementation of #24 we are adding the Apache-Commons Validator 1.6 library to the project, which will allow use of the apache commons library to be used for Date validation. We can definitely use the SimpleDateFormat class, but it'll ultimately be choice of the person improving the implementation. You can look up more info on the  Apache-Commons Validator DataValidator class at https://commons.apache.org/proper/commons-validator/apidocs/org/apache/commons/validator/routines/DateValidator.html

**Comment by rsanchez-wsu** [comment]
@eSweetTech That sounds good.  Please make sure that the license of commons-validator is compatible with our project license and make sure to capture the information in a comment to #10 so that @randymusser can include it in the final report/documentation.
