### ISSUE TITLE
Study Profile Page Remove Dialog and Replace

### ISSUE THREAD

**Issue by mikeknows** [rsanchez-wsu/RaiderPlanner#362]
<img width="736" alt="issue" src="https://user-images.githubusercontent.com/10665041/46691095-0a3ada80-cbd2-11e8-9388-09b6c2584e9c.png">
<b>Problem</b>

The dialog is unnecessary and there are no directions as to how to bring the dialog menu up, the average user may be unaware that it's necessary to double-click on the profile name

<b>Solution</b>
When highlighted with left-click, display the 'set as current' option and the information in the main window of the Study Profile page.
.

**Comment by mikeknows** [comment]
Group1 will work on this.

**Comment by rsanchez-wsu** [comment]
@mikeknows I like this idea.  Make sure that there is sufficient work to be done given the size of the team.
