### ISSUE TITLE
Fix the unused notes array list within the Task class

### ISSUE THREAD

**Issue by RandyForte** [rsanchez-wsu/RaiderPlanner#37]
There is an unused ArrayList of notes in the Task class. It seems like there was going to be a feature for adding notes to tasks but the feature was not implemented.

To me it seems there are two ways to handle this:

1. Remove the notes array list and pretend it never existed.

2.Implement the feature of adding notes to task as well as displaying them as needed. The notes could also be implemented into requirements (note that both Task and Requirement inherit from ModelEntity). Or the notes could be moved and added to the assignments.

**Comment by Smith-Jake** [comment]
I will begin working on this issue
