### ISSUE TITLE
Chat feature: Name input change

### ISSUE THREAD

**Issue by CMorgan272** [rsanchez-wsu/RaiderPlanner#372]
When using the chat feature it asks the user for "Your Name" which can be any input and then asks the user for the "Host User Name" which can be any input. I believe that the end goal of this feature is to allow peer to peer chat between users of RaiderPlanner on the same network or through a web based design. The issue I am addressing arises with the fact that when a user creates their account they do not have to put a name in only their W number. So that basically locks the chat feature for them because they do not have a "Name" that the program can Identify them with. I suggest that we make the chat feature ask for "Your W number" and "Host W number" and enforce the correct inputs. I also feel as though it would be nice if the "Your W number" field was automatically set to the current users W number as well. This change will make it easier as we move toward a database design were all users of RaiderPlanner will be identified by their W number "Primary Key".

**Comment by CMorgan272** [comment]
I would like to work on this.

**Comment by rsanchez-wsu** [comment]
This sounds like a good idea.
