### ISSUE TITLE
Too many unneeded MessageBoxes.

### ISSUE THREAD

**Issue by D-B-Cooper** [rsanchez-wsu/RaiderPlanner#377]
There are currently unneeded message boxes in the program. One example is when the user imports a file, then a messageBox says that it is successful. 

![notification before](https://user-images.githubusercontent.com/42809717/47247471-f5c8c000-d3d1-11e8-81f4-ecc724c097d3.PNG)

This requires user interaction, and is not aesthetically pleasing. One solution is to use a notification similar to the notifications standard in Windows 10. Shows briefly in the bottom right corner and looks nice. See example below (ignore that it says warning).

![new error message](https://user-images.githubusercontent.com/42809717/47247518-40e2d300-d3d2-11e8-8408-efec94ca4369.png)

**Comment by D-B-Cooper** [comment]
@gagegage926 and I will take this.

**Comment by rsanchez-wsu** [comment]
Closed by #416
