### ISSUE TITLE
Selecting current date on popup calendar (new task, requirement, etc)

### ISSUE THREAD

**Issue by D-B-Cooper** [rsanchez-wsu/RaiderPlanner#384]
The popup calendar used when selecting a date (like deadline for new task) does not pass the correct date once the page is saved. It jumps nearly a year forward. 

To recreate the bug, just go make a new task. When you select a date for deadline, hit ok and look at the date saved.

**Comment by westfall123** [comment]
Tyler and I will claim this issue.
