### ISSUE TITLE
Fix source and test package structure

### ISSUE THREAD

**Issue by rsanchez-wsu** [rsanchez-wsu/RaiderPlanner#4]
The Java source files and additional resource files contained under the `src` and `Test` directories use a package structure which does not conform to Java conventions and best practices.  The existing packages need to be renamed to use names with all lowercase letters (e.g., `Model` -> `model`) and all of the current top-level packages need to be placed in a package hierarchy under the package `edu.wright.cs.raiderplanner`.

Take care when making the change are there are numerous references in the code which point to specific file resources that depend upon the current package hierarchy.  It will be necessary to handle those references intelligently and thoroughly test the program after the changes have been made.

**Comment by Shree9** [comment]
Hi, 

I will take care of this issue.

-Shree

**Comment by rsanchez-wsu** [comment]
@Shree9 You will want to look into Eclipse's (or your IDE's) refactoring capabilities in order to make this change.  If you try to do it all by hand it will take a very long time and you are likely to miss something important.

**Comment by Shree9** [comment]
Hi, 

Unfortunately, I have to drop this class. So, I will not be able to continue working on this issue. Sorry.

-Shree

**Comment by HRRichter** [comment]
I'll start to work on this.

**Comment by rsanchez-wsu** [comment]
@HRRichter How is this coming along?
