### ISSUE TITLE
Fix window sizing

### ISSUE THREAD

**Issue by RachelHill8** [rsanchez-wsu/RaiderPlanner#40]
I think the application should adapt to the window size. I would like the text size and icons to grow and shrink as the window changes. This will remove a lot of blank space when the window is full screen as well as better adapt when it is smaller. 

Currently when shrinking the application down so the icons are in one row on the main page there is an overlap with the text "First Year Gryffindor"  This would be fixed when adding the screen adaption.

**Comment by rsanchez-wsu** [comment]
@RachelHill8 window sizing is something that needs to be considered within the context of the entire UI.  I would be comfortable with this issue driving exploration and discussion of the specific issues (like the one you mention in your initial summary) and some alternative solutions, but we need to expand to considering the entire UI.  Once we have that, then this and other specific design changes can be properly fleshed out.

One thing to consider in particular is that we have open issues for mobile deployment, #26, and web deployment, #27, and we would need to consider any font and UI element scaling in light of how it would affect those platforms as well.

We also need to consider whether the UI needs to enforce certain minimums, like a minimum window dimension below which the application does not allow the window to shrink any more.

**Comment by RachelHill8** [comment]
I have currently been working on parts of this issue and have added a minimum screen width.  I have also added so when you first run the project it will open in full screen.  I personally am a fan of full screen but I want to know if anyone else has any preferences. I haven't committed any changes yet just on my local machine. 

The main issue I want to fix is making the modules responsive but I am having hard time figuring out exactly where in the code the modules are brought into the UI. I know it's somewhere between the UIManger.java and the Module.java. I don't know if anyone has figured it out or is willing to lead me in a different direction.

**Comment by Aashishkebab** [comment]
Oddly enough, I think I found it inside the MenuController.java in the View package. 

The line begins with "vbox.getChildren().add(badge).
It's line 190 for me but might be different for you. 
The code block after that adds the modules to the dashboard I think. Or at least, it definitely adds the "View" buttons to the container that contains the modules.

**Comment by RachelHill8** [comment]
Thanks a lot! I've been searching through the code forever and was hoping someone might have seen it. I think it was the badge naming that threw me off.
