### ISSUE TITLE
Contact us page for the RaiderPlanner website

### ISSUE THREAD

**Issue by adhithan96** [rsanchez-wsu/RaiderPlanner#402]
A great program needs a reliable contact us page. A reliable contact us page should be easy and straightforward for average user to understand. Our plan is to implement a contact us section in the RaiderPlanner website. In the contact us section, the user will be provided with a text box for their valuable input. Users can provide any feedback related to the program or constructive criticism.They will also be provided with the opportunity to add their name and their email address. If the user likes, they could also add files and pictures to the submit form. Then once user submits the form, that form will be sent to Mr. Roberto Sanchez or to a dedicated email for feedback purposes.

**Comment by rsanchez-wsu** [comment]
@adhithan96 I recommend that you consider a different issue.  To start with, I do not think that the amount of work that would be involved in this would rise to the level of a project assignment.  Additionally, it is unlikely that you will be able to get the feedback mechanism working at all, as I do not think that GItHub allows sending email from their servers and we do not employ an external mail service that we could use for this purpose.
