### ISSUE TITLE
Currently no unit test code coverage for the TimetableEvent.java model

### ISSUE THREAD

**Issue by adamarthurcone** [rsanchez-wsu/RaiderPlanner#403]
There is currently no code coverage for the TimetableEvent.java model. Implement adequate unit tests to validate existing functions in TimetableEvent.java. Unit testing functions for correctness is critical to software deployment process. The resolution of this issue would improve confidence in the program as a whole.

**Comment by rsanchez-wsu** [comment]
This looks like a good idea to implement.
