### ISSUE TITLE
No cancel button for account creation.

### ISSUE THREAD

**Issue by Neon-Skyfire** [rsanchez-wsu/RaiderPlanner#406]
Kind of similar to #303 and #324, but when the user goes to create another new profile after they already an existing one, the only options they have are to make a new profile or quit the program entirely.  Since no error is thrown before the program closes, it leads me to believe that the quit button shown on the pop-up just closes the program.   I think there should be a cancel button added that returns the user to the main screen for the account that is already open for use primarily if the create account button was clicked accidentally.  The button could replace the quit button or be placed next to it, although I can't really see a reason for the user to need both.
![image](https://user-images.githubusercontent.com/34351455/48586037-af954c80-e8fc-11e8-9468-7ef21403f197.png)

**Comment by GGanris** [comment]
I'll work on this.

**Comment by Neon-Skyfire** [comment]
I am working on this
