### ISSUE TITLE
Mislabel in create account 

### ISSUE THREAD

**Issue by Mark11212** [rsanchez-wsu/RaiderPlanner#430]
Currently the working version of the project has a mislabel in createAccount.fxml
![createaccount](https://user-images.githubusercontent.com/45154318/48680816-6e0ad880-eb6c-11e8-94ef-21a6a7cc6df5.PNG)

**Comment by rsanchez-wsu** [comment]
@Mark11212 Can you describe the problem in a bit more detail.  I can tell by looking at it that it is wrong, but I am interested to know what you think it should look like when correct.
