### ISSUE TITLE
RaiderPlanner GitHub home wiki page

### ISSUE THREAD

**Issue by adhithan96** [rsanchez-wsu/RaiderPlanner#439]
Currently the home wiki page on GitHub has no information. I am planning to fill the home page with valuable information. That the developers and users might find worthy to read.

**Comment by adhithan96** [comment]
I will be working on this issue

**Comment by rsanchez-wsu** [comment]
@adhithan96 This is too vague.  Please provide a summary of what information you would add and why it would belong on the first page in the wiki.

**Comment by adhithan96** [comment]
I would like to add bit of core information related to the wiki page. Then give a brief summary of history of the Raiderplanner. I believe this information should belong to the first page in the wiki because users before developing something, should understand the core principles of RaiderPlanner.

**Comment by rsanchez-wsu** [comment]
The changes you made seem OK.  Closing this issue.
