### ISSUE TITLE
Fix content overlap on Window resize

### ISSUE THREAD

**Issue by Aashishkebab** [rsanchez-wsu/RaiderPlanner#44]
When resizing the JavaFX window to a relatively small size, the content overlaps. Images will be displayed over text, etc. We can modify the CSS stylesheet to fix this issue, or we can set a minimum window size (though this will create other issues).

**Comment by Aashishkebab** [comment]
I closed this because I realized that Rachel's issue was very similar.

**Comment by rsanchez-wsu** [comment]
@Aashishkebab When closing an issue as a duplicate, please make sure to add the "duplicate" label and specifically mention the other issue which was been duplicated in the closure message.  That helps keep everything properly connected.
