### ISSUE TITLE
Import XML Database Optimization 

### ISSUE THREAD

**Issue by Fahad-n** [rsanchez-wsu/RaiderPlanner#46]
In order to import databases faster, this issue has to be optimized.
Issue:
Under “controller” package - “DataController.java:231”  – function “static private HubFile processNewHubFile(NodeList nList)” - code "if (n.getNodeType() == Node.ELEMENT_NODE)". This line checks the XML database tags inside the reading of the values between the tags. It exists in so many WHILE loops.
Fix:
This function can be optimized and run faster by removing this statement "if (n.getNodeType() == Node.ELEMENT_NODE)" from all the while loops, and start the while loop from "1" to "maxSize -1" to avoid checking for the IF statement so many times. When importing a large database schema it will be a lot faster.

**Comment by rsanchez-wsu** [comment]
@Fahad-n I am not convinced that your approach is better.  I suggest that you (or whoever ends up working on this) read Section 11.5 of the _Introduction to Programming Using Java_ book (and perhaps other available resources on XML processing) and then do a performance comparison.  For the comparison you will need to create a sufficiently large XML dataset that you would be able to measure the difference between the two implementations.  We can talk if you need additional suggestions and guidance on how to going with this.

**Comment by Fahad-n** [comment]
I'm not sure, instead of doing a large XML file. (I'm not sure about my test method), I made a loop that reads test3.xml for 1000 times. With optimized code and non-optimized one and here is the result.  

//regular DataController.java code import test3.xml 1000 times
1st:Time taken: 8818 milliseconds
2st:Time taken: 9036 milliseconds
3st:Time taken: 8588 milliseconds
4st:Time taken: 8677 milliseconds
5st:Time taken: 8522 milliseconds
6st:Time taken: 8535 milliseconds
7st:Time taken: 8201 milliseconds
8st:Time taken: 8501 milliseconds
average:8609.75 milliseconds

//optimized DataController.java code import test3.xml 1000 times
1st:Time taken: 8538 milliseconds
2st:Time taken: 8554 milliseconds
3st:Time taken: 8327 milliseconds
4st:Time taken: 8221 milliseconds
5st:Time taken: 8525 milliseconds
6st:Time taken: 8362 milliseconds
7st:Time taken: 8507 milliseconds
8st:Time taken: 8605 milliseconds
average:8454.875 milliseconds

If my way of testing is right, it is really a slight difference between them.

**Comment by rsanchez-wsu** [comment]
@Fahad-n Can you post your test code?

**Comment by Fahad-n** [comment]
sure, sorry for the lateness. I attached the files.


[DataController_Test.zip](https://github.com/rsanchez-wsu/RaiderPlanner/files/1315715/DataController_Test.zip)

**Comment by Fahad-n** [comment]
@rsanchez-wsu so what do you think Mr. Roborto?

**Comment by rsanchez-wsu** [comment]
@Fahad-n Looking at your timing data, your optimization does not appear to gain much, if any, performance.  I am also not certain that it is a good idea to change the code in this way without the benefit of a robust unit test to ensure we don't break something.  Additionally, the XML data is realistically going to be loaded very infrequently, and certainly not 1000 or more times in succession.  Based on the those things I don't think it makes sense to make a change.  I am closing this issue.
