### ISSUE TITLE
Open calendar in same window as application

### ISSUE THREAD

**Issue by rnunez95** [rsanchez-wsu/RaiderPlanner#47]
The current implementation opens the calendar in a new window rather than using the same window like the other tabs do. It would be suitable to keep the same theme throughout the application, as well as improve overall user experience.
reference #5

**Comment by rsanchez-wsu** [comment]
This also relates to #26 (mobile deployment) and #27 (web deployment).

**Comment by cameronroudebush** [comment]
I will look into this one.
