### ISSUE TITLE
Redundancy Codes

### ISSUE THREAD

**Issue by nguyenvo8** [rsanchez-wsu/RaiderPlanner#48]
**# Description:**
This issue relates to 3 classes in the project which are StudyPLannerController, DataController, and MainController. In the MainController class, the method initialise() is used to load a study planner file. That method will check whether a planner file already exists or not. If the file exists, it will load the data. Otherwise, it will create a new account and assign that account to a new planner file. The else statement in this method is used for creating a new planner file. Since in the StudyPlannerController (SPC) class, its default constructor has the same purpose. It checks whether planner file exists or not and prompt the user to create a new planner file. Also the method exisitingSettingsFile() in DataController class is not implemented which has the same function with the checking condition in initialise() method in MainController class.
**# Solution**

- [ ] Remove line 89 and line 90 in MainController class and replace it with the default constructor of SPC, which will prompt the user to create new account and a new planner file

- [ ] Remove the if-else statement of the StudyPlannerController default constructor and leave the codes of else condition

- [ ] Remove the method existingSettingsFile() method in DataController class

Please also read User Manual and Study Planner Specification in RaiderPlanner folder for more information

**UPDATED:**
After doing couple tests which I commented out the SPC default constructor and also remove the current StudyPlanner.dat file in src folder, then run the program. The purpose of this is to see whether the codes in the default constructor have any effect on the whole program. The result is that there is no effect on the whole program, therefore it needs to be removed.
Also, the account number text field needs to be modified. When the user input special characters, the text field doesn't change or show any signs that the input is invalid except the submit button doesn't work.
**Solution:**

- [ ] Remove the codes in SPC default constructor.

- [ ] Also remove the method existingSettingsFile() in DataController class. initialise() in MainController had taken care of that problem.

- [ ] Leave the initialise() in MainController the same as the origin.

- [ ] In AccountController modify the validateNumber() method so it has the same behavior with other validate methods which the text field turns red when the user uses invalid input.

**Comment by rsanchez-wsu** [comment]
@nguyenvo8 This is an excellent issue write up.

**Comment by DTCartier** [comment]
I can take this one.

**Comment by rsanchez-wsu** [comment]
I just noticed that pull request #70 was from @nguyenvo8 while @DTCartier indicated that he would be working on this.  The two of you need to communicate to determine who will actually make the change.  I will refrain from merging pull request #70 until hear back from both of you about who is going to do what.

**Comment by DTCartier** [comment]
@nguyenvo8 can have this issue since he have the PR in. I'm finishing up issue #32.

**Comment by rsanchez-wsu** [comment]
@DTCartier Thanks!
