### ISSUE TITLE
Update application look and feel

### ISSUE THREAD

**Issue by rsanchez-wsu** [rsanchez-wsu/RaiderPlanner#5]
Related to #3, it is also necessary to update the application look and feel to be consistent with the _RaiderPlanner_ moniker.  Items to change include the program icon (currently an image of a pear, as the application was formerly named _PearPlanner_) and default color scheme.  Prior to beginning work on this, please review the project repository and identify if there are other items which should be addressed under this issue.

It would be worth investigating if there are freely-available (i.e., can be used in a free/open source licensed application) images of the WSU mascot which we might be able to use in the application.  Additionally, the default color scheme should conform to the guidelines published by the university Office of Marketing: https://www.wright.edu/marketing/brand/color

**Comment by NathanS1** [comment]
Hey, I'll start looking into this

**Comment by ribar3** [comment]
@NathanS1 do you mind if I take care of the logo? I'm going to be working on the website.

**Comment by rsanchez-wsu** [comment]
@ribar3 , @NathanS1 made the following comment in Slack:

> Go for it, I'm currently in talks with the office of marketing about the use of certain logos and pictures, but if you want to take over the logo, that's fine with me. I've been looking for a small but recognizable logo that's Wright State related, but I haven't come up with much. Just let me know what you find, thanks.

@NathanS1 We don't have Slack set up to send comments back to GitHub, so you need to make sure to respond in the GitHub issue itself or your comment could get lost.

**Comment by rnunez95** [comment]
@NathanS1  @ribar3 I updated the icon to something raider related with issue #3 but feel free to change it.

**Comment by ribar3** [comment]
@rnunez95 thanks for the update - I've got a logo made for the website. Could you please show me the icon?
