### ISSUE TITLE
Replace old start up prompt with load/new file prompt.

### ISSUE THREAD

**Issue by Eric-Levine** [rsanchez-wsu/RaiderPlanner#56]
The old start up window which is a notice for the person grading the program is unnecessary. Replace this with a prompt that allows you to load a specific save file, or create a new one. Could include other options such as load most recent, etc. More ideas welcome. This also removes the need to manually delete or move a save file to start a new one.

**Comment by Eric-Levine** [comment]
I'll work on this myself if that's okay.

**Comment by rsanchez-wsu** [comment]
@Eric-Levine This sounds good.

**Comment by rsanchez-wsu** [comment]
This issue was closed by commit 7ee8ece, but the commit message does not indicate that properly, so I am closing it with this comment.  @Eric-Levine note that the correct syntax is "Fixes" or "Closes" and then the issue number.
