### ISSUE TITLE
Close notification menu when clicked away from

### ISSUE THREAD

**Issue by randymusser** [rsanchez-wsu/RaiderPlanner#57]
The notification menu currently can only be closed by clicking on the notification button. I think the menu should close if you click anywhere else on the planner, given that the menu covers the upper right portion of the page and it is somewhat inconvenient that the notifications when clicked open on the center of the screen, and the only way to close the panel is to click the icon.

**Comment by rsanchez-wsu** [comment]
@randymusser The behavior you describe is an accurate reflection of how the application functions.  However, I am not certain that it is incorrect or that your suggestion is any more correct.  This needs to be researched to identify the current UI/UX best practices and determine if a change needs to be made.

**Comment by NathanS1** [comment]
I'll look into this for project 2. On many popular websites, this is used for drop-down menus, like on Amazon. I think this could work for all menus used from the dashboard.

**Comment by rsanchez-wsu** [comment]
@NathanS1 please also consider whether the change that is made here will improve or degrade the experience for users of a mobile/touch interface (assuming that the current GUI would be the basis for such an interface).

**Comment by Aashishkebab** [comment]
I think that this would improve the experience on mobile interfaces, as this is how mobile interfaces generally behave.

**Comment by Aashishkebab** [comment]
@NathanS1 I see you initiated a successful pull request but this issue wasn't in there. As a result, I have solved it and committed it to my pull request #106.
