### ISSUE TITLE
Change build system from Ant to Gradle

### ISSUE THREAD

**Issue by rsanchez-wsu** [rsanchez-wsu/RaiderPlanner#6]
The current Ant build system does not meet our requirements and so the project build needs to be transitioned to a build based on Gradle.  The Gradle wrapper should be used within the project (instead of depending on the developer to install Gradle as a separate tool in their environment).  For the purposes of this issue, the objective should be to preserve the existing capabilities of the Ant build in a sensible way.  Please ask for additional guidance if there are any questions about what functionality should be preserved or which bits might be candidates for removal as part of the transition.

**Comment by Miller189** [comment]
I'd like to work on this one

**Comment by Miller189** [comment]
@rsanchez-wsu I know you designed these modules for teams but it seems like everyone's kind of claiming an issue for themselves.  Is this a project that I should try to rally one or two other students to collaborate with from the start? From the look of it, it's going to take me a while to parse all the code by myself and get a sense of the scope of the problem. Additionally, it looks like decisions made during this step are going to affect design possibilities later on, so it seems appropriate to involve other students who could potentially be dealing with the consequences of these decisions.

**Comment by RandyForte** [comment]
If you are looking for someone to collaborate with on this I would be happy to help.

**Comment by Miller189** [comment]
@RandyForte That'd be great!

**Comment by rsanchez-wsu** [comment]
@Miller189 You have hit the nail on the head.  I expect that this will be a rather substantial task and you are correct in your assessment that decisions made as part of this task will have effects throughout the rest of the project.  I expect that a team of 3-4 might make sense, but I will leave it to you to decide.

**Comment by RandyForte** [comment]
@Miller189 Awesome feel free to message me on slack I'm forte.

**Comment by rsanchez-wsu** [comment]
Note that issue #23 calls for adding a new capability to the current `build.xml`.  It should be considered part of what is required with the transition to Gradle.  That is, there should be a similar capability in the implemented Gradle build scripts to run/launch the application.

**Comment by barrett-matthew** [comment]
@RandyForte and @Miller189 

We talked briefly after class yesterday about collaborating on this issue. If you're still looking for a third person, let me know and we can start hammering this out.

**Comment by Bhulbert2096** [comment]
If you guys are still looking for a fourth person to work on this issue I would love to join. Feel free to message me on slack. @Miller189  and @RandyForte  and @barrett-matthew
