### ISSUE TITLE
Switch from in situ dependencies to Gradle-based dependencies

### ISSUE THREAD

**Issue by rsanchez-wsu** [rsanchez-wsu/RaiderPlanner#7]
The current approach of having all project dependencies (i.e., jar files) located in the `lib` directory within the repository is sub-optimal.  The `lib` directory and its contents need to be removed from the project and the project dependencies instead expressed via Gradle's dependency resolution mechanism.  The initial effort should preserve all of the existing dependencies at their current revisions.

Note: #6 must be completed before work on this issue can begin.

**Comment by Miller189** [comment]
Hey I'd like to do this one next if that's cool
