### ISSUE TITLE
Minor tweaks to website content

### ISSUE THREAD

**Issue by rsanchez-wsu** [rsanchez-wsu/RaiderPlanner#81]
The following tweaks need to be made directly to the website content or in some way related to it:

- `Copyright © RaiderPlanner Contributors 2017` needs to become `Copyright © 2017 RaiderPlanner Contributors`
- The AUTHORS link currently returns a 404 error so the file needs to be linked to the code repository, instead of a link relative to the web content `/docs` directory
- The PHOTO-CREDITS file is treated like a binary file by the GitHub web cluster, so it needs be given an extension
- The README.md in the code repository needs a link to the website

**Comment by klemmert** [comment]
Can I claim this issue as well as the issue I created and make that my project 2?

**Comment by klemmert** [comment]
@rsanchez-wsu I have a few questions:
-what exactly do you mean by linking to the code repository? Do you mean link it to the github site?
-what extension were you wanting to give PHOTO-CREDITS? .md?

**Comment by rsanchez-wsu** [comment]
This was fixed by pull request #140
