### ISSUE TITLE
Implement getDuration() method in Model.Event

### ISSUE THREAD

**Issue by rsanchez-wsu** [rsanchez-wsu/RaiderPlanner#88]
Currently, three of the subclasses of `Model.Event` (`TimetableEvent`, `ExamEvent`, and `Activity`) implement a method called `getDuration()`.  This results in having to use reflection (i.e., `instanceof`) to determine when an `Event` object is of a sub-type which implements `getDuration()`.  This is poor design.

The `Event` class needs to implement a `getDuration()` method that returns a default duration of zero (which should be specified via a constant in the `Event` class).  The `getDuration()` methods in `TimetableEvent`, `ExamEvent`, and `Activity` need to marked with the `@Override` annotation to indicate that they override the superclass method.

Any occurrences of `instanceof` involving sub-types of `Event` should be simplified to simply call the `getDuration()` method without first casting to a sub-type of `Event`.

**Comment by eSweetTech** [comment]
I'll look into this
