### ISSUE TITLE
Calendar size bug

### ISSUE THREAD

**Issue by Aashishkebab** [rsanchez-wsu/RaiderPlanner#91]
<img width="741" alt="screenshot_20171006-150537" src="https://user-images.githubusercontent.com/25588487/31294752-20913634-aaaa-11e7-9982-b85f9608b541.png">
There is a bug with the calendar. When you resize the window while still in the Study Dashboard, and theen switch to calendar view, the calendar has shrunk.

**Comment by Aashishkebab** [comment]
It seems like this causes sizing in all screens to get messed up, not just the calendar.
<img width="950" alt="screenshot_20171006-155714" src="https://user-images.githubusercontent.com/25588487/31296159-4fcd716a-aaaf-11e7-95f7-0f24106f6600.png">

**Comment by RachelHill8** [comment]
I can try to work on this. I think the bug was started with my window resizing anyway.

**Comment by Aashishkebab** [comment]
Every time you resize the window, then exit and re-enter a screen with a view, the view gets even smaller than before, till eventually it becomes extremely tiny. It shrinks logarithmically.

<img width="955" alt="screenshot_20171012-173410" src="https://user-images.githubusercontent.com/25588487/31520385-a95dbf0a-af73-11e7-8f03-3f662d2cd0a0.png">

It affects the dashboard title stuff as well (my dashboard looks different because I'm working on changing it, but notice the title is cut off).
<img width="955" alt="screenshot_20171012-173406" src="https://user-images.githubusercontent.com/25588487/31520400-b77b64f2-af73-11e7-9c76-17040cc97e18.png">

**Comment by cameronroudebush** [comment]
@RachelHill8 I am not sure if you are still working on this but I ran across this and found that removing lines 238 - 245 in MenuController.java fix most of the resizing issues but then on the dashboard the module view gets shifted over.

```
this.mainContent.getColumnConstraints().add(
		new ColumnConstraints(
				Control.USE_COMPUTED_SIZE,
				Double.POSITIVE_INFINITY,
				2000,
				Priority.ALWAYS,
				HPos.CENTER,
				true));
```
