### ISSUE TITLE
FileChooser bug

### ISSUE THREAD

**Issue by Aashishkebab** [rsanchez-wsu/RaiderPlanner#93]
The FileChooser system at the beginning works _only_ if the 'startup folder' "saves" exists. Otherwise, if this folder doesn't exist, an error is thrown, and the program will not proceed beyond the initial dialog. There needs to be a try-catch to check whether the folder exists, otherwise make it or something. This seems to be a major bug.

**Comment by rnunez95** [comment]
I can take care of this bug.

**Comment by Eric-Levine** [comment]
I'm pretty sure this is a pretty easy fix. I'll probably going to be working with the startup prompt again for the 2nd project, so I can fix that when I go back over it to clean it up, if you're not doing it for your project @rnunez95

**Comment by Aashishkebab** [comment]
Honestly it should be a fairly simple fix. One possibility could be a try-catch statement, where if the folder doesn't exist, then it is either created or the program starts the FileChooser in a different location.

**Comment by rnunez95** [comment]
I was going to use this for project 2. As part of this I was going to check all other file read/writes to make sure this is the only instance that there is a try catch block missing.
@Eric-Levine
