### ISSUE TITLE
Create a downloadable file of the project on the website

### ISSUE THREAD

**Issue by klemmert** [rsanchez-wsu/RaiderPlanner#95]
Get the most recent _working_ files of the Raider Planner and make a downloadable zip file for the user on the website to download on the download page. This issue will need to be updated every time there is an mass update and only when the project is running properly.

This also relates to issue #81

**Comment by klemmert** [comment]
I would also like to claim this issue

**Comment by rsanchez-wsu** [comment]
This was fixed by pull request #140
